### ISSUE TITLE
#TK12-Definir los destinos

### ISSUE THREAD

**Issue by FissoreAylen** [AgustinFleitas19/Proyecto-Integrador-TSDWAD-PT2#19]

**Comment by MilagrosLeiva** [comment]
Definí los primeros destinos en base a lo que se armó para el trabajo anterior.

**Comment by MilagrosLeiva** [comment]
NOA: Jujuy, Salta
NEA: Misiones
CUYO: Mendoza
CENTRO: Córdoba
PATAGONIA: Rio Negro.
